### ISSUE TITLE
Getting: undefined method `strip' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by wkoszek** [minivan/middleman-spellcheck#27]
I'm getting this trace from my attempt to build a Dockerfile for my home website.

This is Ubuntu 15.04 with Ruby 2.2.4 built via RVM.

We'll have to debug this guy.

```
  spellcheck  Running spell checker for /blog/2012/02/02/book-secret/
/nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/spellchecker.rb:57:in `block (2 levels) in query': undefined method `strip' for nil:NilClass (NoMethodError)
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/spellchecker.rb:51:in `each'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/spellchecker.rb:51:in `block in query'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/spellchecker.rb:48:in `popen'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/spellchecker.rb:48:in `query'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/spellchecker.rb:87:in `check'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/extension.rb:110:in `run_check'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/extension.rb:104:in `spellcheck_resource'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/extension.rb:31:in `block in after_build'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/extension.rb:29:in `each'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-spellcheck-0.9.2/lib/middleman-spellcheck/extension.rb:29:in `after_build'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/extension.rb:159:in `block in bind_after_build'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/cli/build.rb:72:in `build'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in `method_missing'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/bin/middleman:23:in `load'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/bin/middleman:23:in `<main>'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `<main>'
makefile:4: recipe for target 'render' failed
make: *** [render] Error 1
```

**Comment by wkoszek** [comment]
Tried to reproduce, but failed:

```
nobody@18583ba4e20c:/me$ middleman spellcheck source/blog/2012-02-02-book-secret.md
# KC ------------ site building started -----------
# Build: true
== Unknown Extension: graphviz
/nonexistent/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/middleman-livereload-3.4.6/lib/middleman-livereload/reactor.rb:14: warning: toplevel constant Mutex referenced by Thread::Mutex
== LiveReload accepting connections from ws://172.17.0.2:35729
  spellcheck  Running spell checker for /me/source/blog/2012-02-02-book-secret.md
```

**Comment by wkoszek** [comment]
Kept playing with Dockerfile development. I think there might be a relationship between these failures and the lack of stuff in `spellcheck-allow` sections. Need to run some experiments today.
